### ISSUE TITLE
Segmentation fault when accessing variables outside in a module.

### ISSUE THREAD

**Issue by hongzhidao** [nginx/njs#443]
Hi, @xeioex 

1. segmentation fault when accessing variables outside in a module.

test.js
```
var a = 1
import foo from "foo.js"
```

foo.js
```
export default a
```

2. I wonder if a module can access global variables outside?
    if not, is it possible to access global variables in modules?

3. what's the `global` only introduced in njs for?

Thanks.

**Comment by drsm** [comment]
@hongzhidao 

Hi!

3. 
```js
>> global === globalThis 
true
```
2.

> I wonder if a module can access global variables outside?
> if not, is it possible to access global variables in modules?

Yes. Anything defined in global scope will be a property of the `globalThis` object.

https://github.com/nginx/njs/issues/300#issuecomment-612049416

1. 
```js
var a = 1
import foo from "foo.js"
```
In such case `a` is not a global, because module scopes are independent.

**Comment by hongzhidao** [comment]
@drsm Thanks!

In non-module mode, variables declared in the top scope are the same as `global.{var-name}`.
In module mode, only global variables like`global.{var-name}` can be accessed across modules.
Do I understand this correctly?

Btw, I want to register global variables to be accessed anywhere.
Is the only way like this?
```
var m1, m2;
global.m1 = m1;
global.m2 = m2;
```

**Comment by drsm** [comment]
@hongzhidao 

> Do I understand this correctly?

Yes.

> Is the only way like this?

Yes.

> Btw, I want to register global variables to be accessed anywhere.

```js
$ cat mod.js 
export default null;
// register globals
globalThis.GlobalOne = 1;
globalThis.GlobalTwo = { test: 1 };

$ cat main.js 
import dummy from './mod.js';
// does not work in njs looks like a bug:
console.log(GlobalOne++, GlobalTwo, GlobalOne);
// an explicit way works fine:
console.log(globalThis.GlobalOne++, globalThis.GlobalTwo, globalThis.GlobalOne);
```

**Comment by hongzhidao** [comment]
@drsm 

```
$ cat mod.js
export default function() {
    console.log(a++)
};

$ cat main.js
import mod from './mod.js';
globalThis.a = 1
mod()
console.log(a)
```

```
$ qjs main.js
1
2
```

It seems if a variable does not exist, finally, it continues to find from the `globalThis` object, right?
If yes, as long as users want to access a global variable, it's enough to write like `var_name` without namespace `globalThis`.

**Comment by hongzhidao** [comment]
@xeioex @drsm 

Take a look again.
```
globalThis.a = 1

function foo() {
    console.log(a++)
}

foo()
console.log(a++)
```
it works well in chrome. but throws errors like above in njs.
```
Thrown:
ReferenceError: "a" is not defined
    at console.log (native)
    at foo (test.js:4)
    at main (test.js:7)
```

**Comment by drsm** [comment]
> It seems if a variable does not exist, finally, it continues to find from the globalThis object, right?

Yes.

> If yes, as long as users want to access a global variable, it's enough to write like var_name without namespace globalThis.

An explicit `globalThis['var_name']` will reference a global variable only, but `var_name` may be shadowed in an inner scope:

```js
$ cat main.js 
var GlobalOne; // module scope

import dummy from './mod.js';
console.log(GlobalOne++, GlobalTwo, GlobalOne);
console.log(globalThis.GlobalOne++, globalThis.GlobalTwo, globalThis.GlobalOne);
```
```bash
$ node --use-strict main.js 
NaN { test: 1 } NaN
1 { test: 1 } 2
```

**Comment by xeioex** [comment]
@drsm, @hongzhidao 

BTW

```
import dummy from './mod.mjs';
console.log(GlobalOne, GlobalTwo);
```

works well. 

The problem is `++` and `--` are implemented differently and is not working as expected for global references.

**Comment by hongzhidao** [comment]
@xeioex 
Here's a real-world example.
```
$ cat test.js
import jwt from './jwt.js'
import http from './http.js'

globalThis.jwt = jwt
globalThis.http = http

http.check()


$ cat jwt.js
var jwt = {}

jwt.verify = function() {
    return true
}

export default jwt


$ cat http.js
var http = {}

http.check = function() {
    jwt.verify()
}

export default http
```

It would be great to access another module in one module without namespace `globalThis`,  but it caused core-dump.

**Comment by xeioex** [comment]
@hongzhidao 

>It would be great to access another module in one module without namespace globalThis

BTW, why not import jwt directly into http module?

test.js
```
import http from 'http.js';

http.check()
```

http.js
```
import jwt from 'jwt.js';

var http = {}

http.check = function() {
    jwt.verify()
}

export default http;
```

jwt.js
```
var jwt = {}

jwt.verify = function() {
    console.log('verify');
    return true
}

export default jwt;
```

```
njs  test.js 
verify
```

**Comment by hongzhidao** [comment]
@xeioex 
We have integrated njs with Unit by the template literal. For example:
```
"share": "`/www/html${uri}`"
```
It's basic usage. We are going to support custom functions, the way of the module is a good choice.
```
# taggled template
"if": "http.check`...`" 
```
Here we need two modules `jwt.js` and `http.js`,
but it's different from nginx, since Unit configuration is updated dynamically.
We must manage these modules by APIs. On the runtime phase, It's stored in memory, not a file.
So we can't use the import way.

We also do something in initialization. Such as:
```
import jwt from './jwt.js'        // more details in the below
import http from './http.js'

globalThis.jwt = jwt
globalThis.http = http
```

The above import in initialization will have to be changed, I guess njs needs support for how to import modules from memory.
It would be great if we can get rid of file reading from njs source code as you did recently that introduced `external`.

**Comment by xeioex** [comment]
@hongzhidao 

> The above import in initialization will have to be changed, I guess njs needs support for how to import modules from memory.

What about the following proposal?

host is able to [define](https://github.com/nginx/njs/blob/master/src/njs.h#L188) custom function for open, read and write

As a result Unit will be able to redirect reading from a file to its own shared memory.

**Comment by hongzhidao** [comment]
> host is able to define custom function for open, read and write

Is it related to `event loops`? If yes, Can you show an JS example?

Note our intention is to load strings from memory into modules that can be used as normal modules. Like that:
```
# it's better to preload modules by C APIs instead of the below two imports
import jwt from "this is related jwt code"
import http from "this is related http code"

globalThis.jwt = jwt
globalThis.http = http
```
And it's better to be registered by C APIs. I did a patch to make it pass. (It's just for demo)
https://gist.github.com/hongzhidao/17d45b1db99b73611c4840559eacb4f9

**Comment by xeioex** [comment]
>Can you show an JS example?

```c
static njs_vm_ops_t njs_console_ops = {
...
    njs_console_open, // open(external, file_path)  external will be the same as vm_options.external
    njs_console_read, // read(external, fd, buf, size), 
    njs_console_write, // write(external, fd, buf, size),
    ..
};

...

vm_options.ops = &njs_console_ops;
 vm_options.external = &njs_console;
 
vm = njs_vm_create(vm_options);
..

```

Njs will use custom ops whenever possible. As a result you will be able to redirect all IO to memory strings without introducing additional mechanisms in njs.

**Comment by hongzhidao** [comment]
@xeioex 
Assume that I have an array that stores the information about modules to be registered.
```
# C code in Unit software.

typedef struct {
     nxt_str_t  name;  /* module name */
     nxt_str_t  text; /* js code */
} nxt_js_module_t;

nxt_array_t  *modules;  /* of nxt_js_module_t */
/* .. set modules .. */

vm = njs_vm_create(vm_options);

/* preload modules by C APIs */
for (i = 0; i < modules->nelts; i++) {
     vm->load_module(modules[i].name, modules[i].text);  // we need something like load_module API to register module.
}

njs_vm_compile(...);
```
What we need to do is to pre-load modules stored in Unit while creating njs vm.

I can't get how to use `njs_vm_ops_t` to do it.
```
typedef struct {
    njs_set_timer_t                 set_timer;
    njs_event_destructor_t          clear_timer;
} njs_vm_ops_t;
```

**Comment by xeioex** [comment]
@hongzhidao 

```c
typedef struct {
     nxt_str_t  name;  /* module name */
     nxt_str_t  text; /* js code */
} nxt_js_module_t;

nxt_array_t  *modules;  /* of nxt_js_module_t */
/* .. set modules .. */

vm = njs_vm_create(vm_options);
```

Looks good.

Do we really need a separate vm->load_module()?

Instead, when parsing import statement njs may lookup nxt_js_module_t table while looking for a module, before reading from file system.

**Comment by hongzhidao** [comment]
> Do we really need a separate vm->load_module()?

I'm not sure, it's for showing what Unit expects, I guess there's a better way.

My thoughts are:
1. separating module parsing from import statement. while parsing import statement, njs only save the information.
   after calling njs_parser(), parsing saved modules. actually, it's the QuickJS way.
   anyway, do the refactor of getting rid of file reading in the import statement first.
   and if we want to support more module syntax in the future, I guess the current way is limited.
2. looks that `vm->addons` is a good place to store related modules information.

**Comment by xeioex** [comment]
Hi @hongzhidao, @drsm 

Take a look at the [patch](https://gist.github.com/xeioex/e1b0bb2de34aa97ad1dbaa11b4e71c9f).
The patch adds the support of custom module loader callbacks.

```
...
this patch introduces HostResolveImportedModule support.
When vm->options.ops->module_loader is provided, a module lookup
and compilation is delegated to this callback.
```

The module_loader is called with `vm`, `vm->external` and `module` name as arguments.

The default loader is [here](https://gist.github.com/xeioex/e1b0bb2de34aa97ad1dbaa11b4e71c9f#file-github443-patch-L1047).

**Comment by drsm** [comment]
@xeioex 

It looks like recursive imports are not supported:
```js
$ tail -v -n +1 a.js b.js c.js 
==> a.js <==
import b from 'b.js';
export default 1;

==> b.js <==
import a from 'a.js';
export default 1;

==> c.js <==
import a from 'a.js';
import b from 'b.js';
$ build/njs c.js 
Thrown:
ReferenceError: cannot access "./a.js" before initialization
    at ./b.js (./b.js:1)

```

BTW,
```js
$ tail -v -n +1 a.js b.js c.js 
==> a.js <==
import b from './b.js';
export default 1;

==> b.js <==
import a from './a.js';
export default 1;

==> c.js <==
import a from './a.js';
import b from './b.js';
$ build/njs c.js 
Segmentation fault (core dumped)
```

**Comment by hongzhidao** [comment]
@xeioex 
The patch is awesome!
Is my understanding correct?
1. The issue of `globalThis` has been fixed, I tested it, it works well.
2. Njs supports custom module loader.
3. Based on the patch, we can load modules from memory.
    But if we still have to load codes like that:
    ```
    import http from "http module code";
    import jwt from "jwt module code"
    ```
It's fine for me, I'll try it first, then let me see if C API to preload modules is necessary.

**Comment by hongzhidao** [comment]
@xeioex 
Thanks for this great job, I can't wait to test it with Unit :)

**Comment by xeioex** [comment]
@hongzhidao 

> The issue of globalThis has been fixed, I tested it, it works well.

To be exact, 

```
import dummy from './mod.mjs';
console.log(GlobalOne, GlobalTwo);
```

works well

```
import dummy from './mod.mjs';
console.log(GlobalOne++); // and other modifying operations like +=, -=, ...
```

is not fixed yet, because it is a separate issue. It requires implementing `GLOBAL SET` instruction and modifying generator to support setting global references.

**Comment by xeioex** [comment]
Hi @drsm,

Thanks for your valuable feedback.

Take a look at the second [iteration](https://gist.github.com/xeioex/dc0de196ca915c2f6b17063a5e6c8cfe). 

Cyclic imports, relative paths, and export default sinking was fixed.

**Comment by xeioex** [comment]
Hi @hongzhidao,

[FYI](https://gist.github.com/xeioex/dc0de196ca915c2f6b17063a5e6c8cfe#file-github443_2-patch-L88), import binding are not automatically become `globalThis` properties (as it is in Node.js).

**Comment by drsm** [comment]
Hi @xeioex,
Patch works well, thanks.

Just found a bug:
```js
$ tail -v -n +1 b.js c.js 
==> b.js <==
console.log('b1');
export default (() => console.log('b2'))();
console.log('b3');

==> c.js <==
import b from './b.js';
console.log('c1');
$ build/njs c.js 
b1
b3
b2
c1
$ node c.js 
b1
b2
b3
c1

```
Not sure it worth to fix it this time, IMO #420 is the better target
